apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 058841532389.dkr.ecr.us-west-2.amazonaws.com/shopping-site-phones:6f34d1ebfbe15515603c0a11337315480c830ee3
        ports:
        - containerPort: 80
