apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 058841532389.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlegrocery:6f34d1ebfbe15515603c0a11337315480c830ee3
        ports:
        - containerPort: 80
